name: Ghost
type: class
img: icons/svg/upgrade.svg
system:
  description: A Resonance Echo Adrift Without A Body
  experience_clues:
    - You exacted vengeance upon those whom you deem deserving.
    - You expressed your outrage or anger.
    - You struggled with issues stemming from a deadlock.
# First ability is the starting special.
abilities:
  - name: Resonance Echo
    description: >-
      You are now a psychedelic being of swirling multicolored vapor that resembles your living
      body and clothes. You may weakly interact with the physical world and vice versa. You're
      vulnerable to paranormal powers and electroplasmic effects. You move about by floating and
      may fly swiftly without tiring. You may slowly flow through small openings as a vapor. You
      change the temperature around you and are mind-bending for the living to behold. You are
      affected by spiritbane charms (take 2 Drain to overcome the repulsion), but not many
      people still carry these. You have less effect under the light of bluetime. Whenever you
      would take Stress, take Drain instead. When you would deadlock a key, choose an echo
      irregularity instead.
  - name: Dissipate
    description: >-
      You can disperse the vapor of your ghostly form in order to pass through solid objects for
      a moment. Take 1 Drain when you dissipate, plus 1 Drain for each feature: It lasts longer
      (a minute—an hour—a day)—you also become invisible—anything that passes through your form
      becomes dangerously electrified or frozen.
  - name: Manifest
    description: >-
      Take 1 Drain to flow through the electroplasmic pathways of the resonance field in order
      to instantly travel to any place you knew intimately in life, or to answer the summoning
      call when compelled.
  - name: Poltergeist
    description: >-
      Take 1 Drain to strongly interact with the physical world for a few moments (as if you had
      a normal body). Extend the reach and magnitude of your interaction to include telekinetic
      force and electroplasmic discharges by taking more Drain (2-6).
  - name: Possess
    description: >-
      You may Attune to the resonance field in order to take control of a living body. When your
      control is challenged, you must re-Attune (risking electroplasmic harm) or leave the body.
      Your control is challenged when: you consume resonance energy from the host—when
      paranormal powers act against you—when the host's will is driven to desperation. You may
      easily and indefinitely possess a hollow or hull that has been prepared for you. If it's a
      hollow, switch to the Vampire playbook. If hull, switch to the Hull playbook, keeping your
      previous action ratings. Immediately take one Hull trait, and fill two memory clocks
      (choose from your previous character's special abilities instead of rolling randomly). To
      remember more than what those two clocks give you will require filling more memory clocks,
      as usual.
  - name: Versatile
    description: Choose a special ability from another source (can be taken more than once).
